version: '2'
services:
  PostgreSQL:
    container_name: postgresql
    restart: always
    image: 'postgres:9.6'
    environment:
      - DEBUG=false
      - DB_USER=hppoc
      - DB_PASS=password
      - POSTGRES_PASSWORD=password
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - './data/peerdata/pssql:/var/lib/postgresql'
      - './data/peerdata/db:/app/db/'
      - './db/explorerpg.sql:/docker-entrypoint-initdb.d/1-schema.sql'
      - './db/updatepg.sql:/docker-entrypoint-initdb.d/2-data.sql'
    networks:
      - byfn-dmcs-t
  Explorer1:
    container_name: explorer
    restart: always
    image: 'xooa/xooa-explorer:3.4'
    environment:
      - >-
        CHANNELS=chlogin-xooa-blockchainpaas-191b2a0a-0b0a-426c-964d-cdf1e09fe1e6:My
        Xooa Ledger
      - ORG=dmcs-t
      - PEER_NAME=peer1.dmcs-t.external.xooa.com
      - ORDERER=orderer2.orderers.cluster1.aws.xooa.com
      - ORDERER_INFO=""
      - TLS_ENABLED=false
      - DATABASE_HOST=postgresql
      - >-
        API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZWVySWQiOiI0ZWRiZGZhMC00MGI3LTQxNjktYWEyZi0xOGZmOTgzNDVmNzciLCJpYXQiOjE2MzkxNjg4OTZ9.4tFHf5TRhLaG8Wn_gVbB1I6qobVjSdThcdB64aXsA9I
      - >-
        EXTERNAL_PEER_STATUS_SET_ENDPOINT=https://dashboardapi.prod1.xooa.io/peer/deployed
    ports:
      - '8080:8080'
    volumes:
      - './crypto-config:/crypto-config/'
    networks:
      - byfn-dmcs-t
    depends_on:
      - PostgreSQL
      - peer1.dmcs-t.external.xooa.com
  peer1.dmcs-t.external.xooa.com:
    image: 'hyperledger/fabric-peer:1.4.9'
    container_name: peer1.dmcs-t.external.xooa.com
    environment:
      - CORE_PEER_ID=peer1.dmcs-t.external.xooa.com
      - CORE_PEER_LOCALMSPID=dmcs-t
      - CORE_CHAINCODE_LOGGING_SHIM=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - >-
        CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn-dmcs-t
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=false
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer1/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer1/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer1/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer1/tls/ca.crt
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dmcs-t.external.xooa.com:7051'
      - 'CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.9'
    command: peer node start
    volumes:
      - >-
        ./crypto-config/peerOrganizations/org.dmcs-t.com/peers/peer1.org.dmcs-t.com/:/etc/hyperledger/crypto/peer1
      - './data/peerdata:/var/hyperledger'
      - '/var/run/:/host/var/run/'
    networks:
      - byfn-dmcs-t
    ports:
      - '7054:7051'
      - '7055:7053'
networks:
  byfn-dmcs-t: null
